(ns SNOBOL4clojure.jvm-codegen
  "Stage 23D — JVM Bytecode Generation

   Compiles SNOBOL4 IR all the way to JVM .class bytecode.
   Each SNOBOL4 program becomes one Java class with a static run() method.
   The JVM JIT compiles the resulting bytecode to native x64 machine code.

   ## Call convention

   Generated classes call EVAL! via INVOKEINTERFACE on clojure.lang.IFn,
   using a static IFn field pre-populated in jvm_codegen itself.  This avoids
   any reference to SNOBOL4clojure.operators in the generated class's constant
   pool (which would fail to resolve at class-load time before the Clojure
   DynamicClassLoader has loaded operators.clj).

   Generated class structure:
     static Object EVAL_FN;   // = jvm_codegen.EVAL_FN (set before run! is called)
     static Object body_N;    // one field per instruction that has a body
     static { body_N = RT.readString(pr-str(body)); ... }
     public static void run() { ... GETFIELD EVAL_FN, INVOKEINTERFACE IFn.invoke ... }

   The generated class only references:
     - java/lang/Object         (always available)
     - clojure/lang/IFn         (always available — part of Clojure runtime jar)
     - clojure/lang/RT          (always available)
     - clojure/lang/ExceptionInfo (always available)
     - SNOBOL4clojure/jvm_codegen (the class that compiled it — always loaded)

   ## Public API

     (compile-to-class src)       → byte[] (JVM .class bytecode)
     (load-program src)           → zero-arg fn (wraps static run() via reflection)
     (run-jvm! src)               → nil (output via *out*)
     (run-jvm-captured! src)      → String (captured stdout)
     (bench-compare-jvm src n)    → {:interpreter-ms :jvm-ms :ratio :outputs-match}
     (clear-class-cache!)         → nil

   ## Design invariant

   Identical output to interpreter (runtime.clj RUN) on every program.
   Validated against 1000+ worm corpus programs.
  "
  (:import [clojure.asm ClassWriter MethodVisitor Label Opcodes]
           [clojure.lang DynamicClassLoader IFn RT])
  (:require [clojure.string          :as str]
            [SNOBOL4clojure.compiler :as comp]
            [SNOBOL4clojure.vm       :as vm]
            [SNOBOL4clojure.env      :as env
             :refer [&STCOUNT &STLIMIT snobol-steplimit!]]
            [SNOBOL4clojure.runtime  :as rt]))

;; ── ASM opcode integer constants ──────────────────────────────────────────────

(def ^:private ^:const ACC-PUBLIC   (int Opcodes/ACC_PUBLIC))
(def ^:private ^:const ACC-STATIC   (int Opcodes/ACC_STATIC))
(def ^:private ^:const ACC-SUPER    (int Opcodes/ACC_SUPER))
(def ^:private ^:const V1-8         (int 52))
(def ^:private ^:const RETURN       (int Opcodes/RETURN))
(def ^:private ^:const ARETURN      (int Opcodes/ARETURN))
(def ^:private ^:const ALOAD-0      (int Opcodes/ALOAD))
(def ^:private ^:const ALOAD        (int Opcodes/ALOAD))
(def ^:private ^:const ASTORE       (int Opcodes/ASTORE))
(def ^:private ^:const GETSTATIC    (int Opcodes/GETSTATIC))
(def ^:private ^:const PUTSTATIC    (int Opcodes/PUTSTATIC))
(def ^:private ^:const INVOKESTATIC (int Opcodes/INVOKESTATIC))
(def ^:private ^:const INVOKEINTERFACE (int Opcodes/INVOKEINTERFACE))
(def ^:private ^:const INVOKEVIRTUAL (int Opcodes/INVOKEVIRTUAL))
(def ^:private ^:const INVOKESPECIAL (int Opcodes/INVOKESPECIAL))
(def ^:private ^:const GOTO         (int Opcodes/GOTO))
(def ^:private ^:const IFNULL       (int Opcodes/IFNULL))
(def ^:private ^:const IFNONNULL    (int Opcodes/IFNONNULL))
(def ^:private ^:const ATHROW       (int Opcodes/ATHROW))
(def ^:private ^:const POP          (int Opcodes/POP))
(def ^:private ^:const DUP          (int Opcodes/DUP))
(def ^:private ^:const ACONST-NULL  (int Opcodes/ACONST_NULL))

;; ── Descriptor constants ──────────────────────────────────────────────────────

(def ^:private OBJ       "Ljava/lang/Object;")
(def ^:private STR       "Ljava/lang/String;")
(def ^:private IFN-DESC  "Lclojure/lang/IFn;")
(def ^:private IFN-CLASS "clojure/lang/IFn")
(def ^:private RT-CLASS  "clojure/lang/RT")
(def ^:private JC-CLASS  "SNOBOL4clojure/jvm_codegen")  ; THIS class
(def ^:private IFN-INVOKE-SIG   (str "(" OBJ ")" OBJ))           ; IFn.invoke(Object)->Object
(def ^:private IFN-INVOKE-2-SIG (str "(" OBJ OBJ ")" OBJ))       ; IFn.invoke(Object,Object)->Object
(def ^:private THROW-SIG  (str "(" STR ")Lclojure/lang/ExceptionInfo;"))

;; ── Static EVAL! IFn reference (set once, used by all generated classes) ─────
;;
;; The generated bytecode does:
;;   GETSTATIC SNOBOL4clojure/jvm_codegen EVAL_FN Lclojure/lang/IFn;
;;   <push body>
;;   INVOKEINTERFACE clojure/lang/IFn invoke (Ljava/lang/Object;)Ljava/lang/Object;
;;
;; This means jvm_codegen is always referenced — which is safe because it's the
;; class that called compile-to-class and is guaranteed already loaded.

(declare EVAL_FN)

;; ── Stage 23E: Inline helper IFn references ───────────────────────────────────
;; These are stored here and referenced by generated bytecode via GETSTATIC,
;; eliminating EVAL! dispatch for the most common IR patterns:
;;   (= VAR val), (= OUTPUT val), (= VAR (op A B)), (LT/GT/LE/GE/EQ A B)
;; Each is a clojure.lang.IFn (or Fn2/Fn1 shape) set at load time.

(declare $$_FN SET_FN PRINT_FN ADD_FN SUB_FN MUL_FN DIV_FN
         LT_FN GT_FN LE_FN GE_FN EQ_FN NEQ_FN SIGNAL_FN
         ;; 23E extension: string concat, SIZE, STR coerce
         CONCAT_FN SIZE_FN STR_FN)

(defn- init-inline-fns!
  "Bind all inline IFn references. Called once when jvm_codegen loads."
  []
  (alter-var-root #'$$_FN   (constantly env/$$))
  (alter-var-root #'SET_FN  (constantly env/snobol-set!))
  (alter-var-root #'PRINT_FN (constantly (fn [v] (println (if (nil? v) "" (str v))) v)))
  (alter-var-root #'ADD_FN  (constantly env/Σ+))
  (alter-var-root #'SUB_FN  (constantly env/subtract))
  (alter-var-root #'MUL_FN  (constantly env/multiply))
  (alter-var-root #'DIV_FN  (constantly env/divide))
  ;; Comparison predicates: return v1 (truthy) on success, nil on failure.
  ;; Mirrors CSNOBOL4/SPITBOL semantics: success = first arg returned, fail = nil.
  (alter-var-root #'LT_FN  (constantly (fn [a b]
    (let [na (env/num a) nb (env/num b)] (when (< na nb) a)))))
  (alter-var-root #'GT_FN  (constantly (fn [a b]
    (let [na (env/num a) nb (env/num b)] (when (> na nb) a)))))
  (alter-var-root #'LE_FN  (constantly (fn [a b]
    (let [na (env/num a) nb (env/num b)] (when (<= na nb) a)))))
  (alter-var-root #'GE_FN  (constantly (fn [a b]
    (let [na (env/num a) nb (env/num b)] (when (>= na nb) a)))))
  (alter-var-root #'EQ_FN  (constantly (fn [a b]
    (let [na (env/num a) nb (env/num b)] (when (clojure.core/= na nb) a)))))
  (alter-var-root #'NEQ_FN (constantly (fn [a b]
    (let [na (env/num a) nb (env/num b)] (when (not (clojure.core/= na nb)) a)))))
  ;; SIGNAL_FN: creates and throws a SNOBOL4 ExceptionInfo signal.
  ;; Stored here so generated classes can call it via IFn.invoke(sig-name)
  ;; without needing to resolve SNOBOL4clojure.jvm_codegen by name in their
  ;; constant pool (which would fail under DynamicClassLoader isolation).
  (alter-var-root #'SIGNAL_FN (constantly
    (fn [^String sig-name]
      (throw (ex-info sig-name {:snobol/signal (keyword sig-name)})))))
  ;; CONCAT_FN: variadic SNOBOL4 string concatenation.
  ;; Mirrors SEQ semantics: if ANY element evaluates to nil, the whole concat
  ;; fails (returns nil). Otherwise coerces all to string and joins.
  ;; Called from generated bytecode as CONCAT_FN.invoke(v1, v2, ...) via IFn.
  ;; For 2-arg concat (most common case), IFn.invoke(Object,Object) is used.
  ;; For N-arg, we use IFn.applyTo via a varargs wrapper — but since most
  ;; real programs do 2-arg (S 'x'), we expose both arities.
  (alter-var-root #'CONCAT_FN (constantly
    (fn
      ;; 2-arg (most common: S = S 'x')
      ([a b]
       (when (and (some? a) (some? b))
         (str (if (nil? a) "" (str a))
              (if (nil? b) "" (str b)))))
      ;; N-arg for longer concat chains
      ([a b & more]
       (let [all (list* a b more)]
         (when (every? some? all)
           (apply str (map str all))))))))
  ;; SIZE_FN: SNOBOL4 SIZE — string length of coerced-to-string value.
  (alter-var-root #'SIZE_FN (constantly
    (fn [s] (count (str s)))))
  ;; STR_FN: coerce to string (used in concat sub-expressions).
  (alter-var-root #'STR_FN (constantly
    (fn [v] (if (nil? v) nil (str v))))))

;; ── 23E: Inline bytecode emitter ─────────────────────────────────────────────
;; Returns true if the body was inlined, false if EVAL_FN fallback needed.
;;
;; Inlinable IR patterns:
;;   (= SYM literal)          — assign integer/string literal to variable
;;   (= SYM SYM2)             — copy variable
;;   (= SYM (op A B))         — binary arithmetic (+,-,*,/) where A,B are sym/lit
;;   (= OUTPUT SYM-or-lit)    — print to stdout
;;   (LT|GT|LE|GE|EQ A B)    — numeric comparison, A/B sym or lit
;;
;; The inline path pushes IFn references stored in the jvm_codegen class as
;; static fields, then calls INVOKEINTERFACE IFn.invoke(Object,Object).
;; This is significantly faster than parsing the body EDN via RT.readString
;; and tree-walking through EVAL!.

(def ^:private JC-IFN-FIELD-SIGS
  "Map from inline-fn var-name string → static field name on jvm_codegen."
  {"$$_FN"    "$$_FN"
   "SET_FN"   "SET_FN"
   "PRINT_FN" "PRINT_FN"
   "ADD_FN"   "ADD_FN"
   "SUB_FN"   "SUB_FN"
   "MUL_FN"   "MUL_FN"
   "DIV_FN"   "DIV_FN"
   "LT_FN"    "LT_FN"
   "GT_FN"    "GT_FN"
   "LE_FN"    "LE_FN"
   "GE_FN"    "GE_FN"
   "EQ_FN"    "EQ_FN"
   "NEQ_FN"   "NEQ_FN"
   "SIGNAL_FN" "SIGNAL_FN"
   ;; 23E extensions
   "CONCAT_FN" "CONCAT_FN"
   "SIZE_FN"   "SIZE_FN"
   "STR_FN"    "STR_FN"})

(def ^:private ARITH-OP->FN
  "Map from IR arithmetic operator symbol → inline field name."
  {'+ "ADD_FN" '- "SUB_FN" '* "MUL_FN" '/ "DIV_FN"})

(def ^:private CMP-OP->FN
  "Map from IR comparison operator symbol → inline field name."
  {'LT "LT_FN" 'GT "GT_FN" 'LE "LE_FN" 'GE "GE_FN"
   'EQ "EQ_FN" 'NE "NEQ_FN"})

(defn- sym-or-lit?
  "True if x is a symbol (variable) or a number/string literal."
  [x]
  (or (symbol? x) (integer? x) (float? x) (string? x)))

(defn- emit-val!
  "Emit bytecode to push a SNOBOL4 value (sym or literal) onto the stack.
   Symbols → call $$_FN.invoke(sym-string) to read from <VARS>.
   Integer/real literals → LDC the boxed value.
   Strings → LDC the string."
  [^MethodVisitor mv cls-name x]
  (cond
    (symbol? x)
    (do (.visitFieldInsn mv GETSTATIC cls-name "$$_FN" IFN-DESC)
        (.visitLdcInsn mv (str x))
        (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                          IFN-INVOKE-SIG true))
    (integer? x)
    (do (.visitLdcInsn mv (long x))
        (.visitMethodInsn mv INVOKESTATIC "java/lang/Long" "valueOf"
                          "(J)Ljava/lang/Long;" false))
    (float? x)
    (do (.visitLdcInsn mv (double x))
        (.visitMethodInsn mv INVOKESTATIC "java/lang/Double" "valueOf"
                          "(D)Ljava/lang/Double;" false))
    (string? x)
    (.visitLdcInsn mv ^String x)
    :else
    (throw (ex-info "emit-val!: not a sym-or-lit" {:x x}))))

(defn- inline-emit!
  "Try to emit optimised JVM bytecode for IR body.
   Returns true on success (body inlined), false if EVAL_FN fallback needed.
   Leaves exactly one value on the stack (the result, possibly null)."
  [^MethodVisitor mv cls-name body]
  (cond
    ;; ── (= OUTPUT val) — print, return val ──────────────────────────────────
    (and (list? body)
         (clojure.core/= (first body) '=)
         (clojure.core/= (second body) 'OUTPUT)
         (sym-or-lit? (nth body 2)))
    (let [val (nth body 2)]
      ;; PRINT_FN.invoke(val) → prints and returns val
      (.visitFieldInsn mv GETSTATIC cls-name "PRINT_FN" IFN-DESC)
      (emit-val! mv cls-name val)
      (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                        IFN-INVOKE-SIG true)
      true)

    ;; ── (= SYM val) — assign literal or variable ────────────────────────────
    ;; Stack: compute val, store to local 0, call SET_FN(sym,val), push local 0 as result.
    (and (list? body)
         (clojure.core/= (first body) '=)
         (symbol? (second body))
         (not (clojure.core/= (second body) 'OUTPUT))
         (sym-or-lit? (nth body 2)))
    (let [sym (second body) val (nth body 2)]
      ;; 1. compute val, store in local slot 0
      (emit-val! mv cls-name val)
      (.visitVarInsn mv ASTORE (int 0))
      ;; 2. call SET_FN.invoke(sym, val)
      (.visitFieldInsn mv GETSTATIC cls-name "SET_FN" IFN-DESC)
      (.visitLdcInsn mv (str sym))
      (.visitMethodInsn mv INVOKESTATIC "clojure/lang/Symbol" "intern"
                        "(Ljava/lang/String;)Lclojure/lang/Symbol;" false)
      (.visitVarInsn mv ALOAD (int 0))
      (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                        IFN-INVOKE-2-SIG true)
      true)

    ;; ── (= SYM (op A B)) — binary arithmetic ────────────────────────────────
    ;; Compute op(A,B), store to local 0, call SET_FN(sym, local0), return local0.
    (and (list? body)
         (clojure.core/= (first body) '=)
         (symbol? (second body))
         (list? (nth body 2))
         (ARITH-OP->FN (first (nth body 2)))
         (sym-or-lit? (second (nth body 2)))
         (sym-or-lit? (nth (nth body 2) 2)))
    (let [sym    (second body)
          [op a b] (nth body 2)
          fn-fld (ARITH-OP->FN op)]
      ;; 1. compute op(a, b), store to local slot 0
      (.visitFieldInsn mv GETSTATIC cls-name fn-fld IFN-DESC)
      (emit-val! mv cls-name a)
      (emit-val! mv cls-name b)
      (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                        IFN-INVOKE-2-SIG true)
      (.visitVarInsn mv ASTORE (int 0))
      ;; 2. call SET_FN.invoke(sym, computed-val)
      (.visitFieldInsn mv GETSTATIC cls-name "SET_FN" IFN-DESC)
      (.visitLdcInsn mv (str sym))
      (.visitMethodInsn mv INVOKESTATIC "clojure/lang/Symbol" "intern"
                        "(Ljava/lang/String;)Lclojure/lang/Symbol;" false)
      (.visitVarInsn mv ALOAD (int 0))
      (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                        IFN-INVOKE-2-SIG true)
      true)

    ;; ── (LT|GT|LE|GE|EQ A B) — comparison predicate ─────────────────────────
    (and (list? body)
         (CMP-OP->FN (first body))
         (sym-or-lit? (second body))
         (sym-or-lit? (nth body 2)))
    (let [[op a b] body
          fn-fld   (CMP-OP->FN op)]
      (.visitFieldInsn mv GETSTATIC cls-name fn-fld IFN-DESC)
      (emit-val! mv cls-name a)
      (emit-val! mv cls-name b)
      (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                        IFN-INVOKE-2-SIG true)
      true)

    ;; ── (= SYM [e1 e2 ...]) — vector concat assign ─────────────────────────
    ;; All elements must be sym-or-lit. Calls CONCAT_FN.invoke(e1,e2) for 2-arg,
    ;; or falls back to EVAL_FN for 3+ args (uncommon).
    ;; Result stored to variable. nil in any element → nil result → stmt fails.
    (and (list? body)
         (clojure.core/= (first body) '=)
         (symbol? (second body))
         (not (clojure.core/= (second body) 'OUTPUT))
         (vector? (nth body 2))
         (every? sym-or-lit? (nth body 2)))
    (let [sym   (second body)
          elems (nth body 2)
          n     (count elems)]
      (if (clojure.core/= n 2)
        ;; Fast path: 2-element concat (most common: S = S 'x')
        (let [[e1 e2] elems]
          ;; 1. compute CONCAT_FN(e1, e2), store to local 0
          (.visitFieldInsn mv GETSTATIC cls-name "CONCAT_FN" IFN-DESC)
          (emit-val! mv cls-name e1)
          (emit-val! mv cls-name e2)
          (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                            IFN-INVOKE-2-SIG true)
          (.visitVarInsn mv ASTORE (int 0))
          ;; 2. call SET_FN(sym, result) — only if non-nil
          (.visitFieldInsn mv GETSTATIC cls-name "SET_FN" IFN-DESC)
          (.visitLdcInsn mv (str sym))
          (.visitMethodInsn mv INVOKESTATIC "clojure/lang/Symbol" "intern"
                            "(Ljava/lang/String;)Lclojure/lang/Symbol;" false)
          (.visitVarInsn mv ALOAD (int 0))
          (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                            IFN-INVOKE-2-SIG true)
          true)
        ;; 3+ element concat: fall through to EVAL_FN
        false))

    ;; ── (= OUTPUT [e1 e2 ...]) — vector concat to OUTPUT ────────────────────
    ;; 2-arg fast path: concat then print.
    (and (list? body)
         (clojure.core/= (first body) '=)
         (clojure.core/= (second body) 'OUTPUT)
         (vector? (nth body 2))
         (every? sym-or-lit? (nth body 2)))
    (let [elems (nth body 2)
          n     (count elems)]
      (if (clojure.core/= n 2)
        (let [[e1 e2] elems]
          ;; 1. concat
          (.visitFieldInsn mv GETSTATIC cls-name "CONCAT_FN" IFN-DESC)
          (emit-val! mv cls-name e1)
          (emit-val! mv cls-name e2)
          (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                            IFN-INVOKE-2-SIG true)
          (.visitVarInsn mv ASTORE (int 0))
          ;; 2. print via PRINT_FN
          (.visitFieldInsn mv GETSTATIC cls-name "PRINT_FN" IFN-DESC)
          (.visitVarInsn mv ALOAD (int 0))
          (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                            IFN-INVOKE-SIG true)
          true)
        false))

    ;; ── (= SYM (SIZE arg)) — assign SIZE result ──────────────────────────────
    (and (list? body)
         (clojure.core/= (first body) '=)
         (symbol? (second body))
         (not (clojure.core/= (second body) 'OUTPUT))
         (list? (nth body 2))
         (clojure.core/= (first (nth body 2)) 'SIZE)
         (sym-or-lit? (second (nth body 2))))
    (let [sym (second body)
          arg (second (nth body 2))]
      ;; 1. SIZE_FN.invoke(arg), store to local 0
      (.visitFieldInsn mv GETSTATIC cls-name "SIZE_FN" IFN-DESC)
      (emit-val! mv cls-name arg)
      (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                        IFN-INVOKE-SIG true)
      (.visitVarInsn mv ASTORE (int 0))
      ;; 2. SET_FN(sym, result)
      (.visitFieldInsn mv GETSTATIC cls-name "SET_FN" IFN-DESC)
      (.visitLdcInsn mv (str sym))
      (.visitMethodInsn mv INVOKESTATIC "clojure/lang/Symbol" "intern"
                        "(Ljava/lang/String;)Lclojure/lang/Symbol;" false)
      (.visitVarInsn mv ALOAD (int 0))
      (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                        IFN-INVOKE-2-SIG true)
      true)

    ;; ── (= OUTPUT (SIZE arg)) — print SIZE result ────────────────────────────
    (and (list? body)
         (clojure.core/= (first body) '=)
         (clojure.core/= (second body) 'OUTPUT)
         (list? (nth body 2))
         (clojure.core/= (first (nth body 2)) 'SIZE)
         (sym-or-lit? (second (nth body 2))))
    (let [arg (second (nth body 2))]
      (.visitFieldInsn mv GETSTATIC cls-name "PRINT_FN" IFN-DESC)
      (.visitFieldInsn mv GETSTATIC cls-name "SIZE_FN" IFN-DESC)
      (emit-val! mv cls-name arg)
      (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                        IFN-INVOKE-SIG true)
      (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                        IFN-INVOKE-SIG true)
      true)

    :else false))

;; ── Signal helpers — called from generated bytecode via INVOKESTATIC ─────────

(defn ^clojure.lang.ExceptionInfo make-signal
  "Create a SNOBOL4 ExceptionInfo. Called from JVM-compiled programs."
  [^String sig-name]
  (ex-info sig-name {:snobol/signal (keyword sig-name)}))

;; ── Class name generation ─────────────────────────────────────────────────────

(defn gen-class-name
  "Generate a stable JVM internal class name for a SNOBOL4 source string.
   The class is in the SNOBOL4clojure package to match jvm_codegen's package."
  [src]
  (str "SNOBOL4clojure/SnobolProg" (format "%08x" (Math/abs (hash src)))))

;; ── Bytecode emitter ─────────────────────────────────────────────────────────

(defn compile-to-class
  "Compile SNOBOL4 source to JVM bytecode.
   Returns byte[] — a valid .class file.

   Generated class layout:
     public static IFn EVAL_FN;     // set externally before run() is called
     public static Object body_N;   // one field per instruction body
     static { body_N = RT.readString(...); ... }
     public static void run() { ... }
  "
  [src]
  (let [bc-vec    (vm/compile-src src)
        n-instrs  (count bc-vec)
        cls-name  (gen-class-name src)
        cw        (ClassWriter. (int ClassWriter/COMPUTE_FRAMES))

        ;; Collect (index, body) pairs for instructions that have a body
        bodies    (into [] (keep-indexed (fn [i {:keys [body]}]
                                           (when body [i body]))
                                         bc-vec))
        body-field (fn [i] (str "body_" i))]

    ;; ── Class header ──────────────────────────────────────────────────────────
    (.visit cw V1-8 (int (+ ACC-PUBLIC ACC-SUPER))
            cls-name nil "java/lang/Object" nil)

    ;; ── Static field: EVAL_FN (IFn, set from Clojure before run() is called) ─
    (.visitField cw (int (+ ACC-PUBLIC ACC-STATIC))
                 "EVAL_FN" IFN-DESC nil nil)

    ;; ── Static fields: 23E inline IFn helpers (set by load-program) ──────────
    (doseq [fld-name (keys JC-IFN-FIELD-SIGS)]
      (.visitField cw (int (+ ACC-PUBLIC ACC-STATIC))
                   fld-name IFN-DESC nil nil))

    ;; ── Static body fields (Object, one per instruction that has a body) ─────
    (doseq [[i _] bodies]
      (.visitField cw (int (+ ACC-PUBLIC ACC-STATIC))
                   (body-field i) OBJ nil nil))

    ;; ── <clinit>: initialise body fields via RT.readString ────────────────────
    (let [ci (.visitMethod cw (int (+ ACC-PUBLIC ACC-STATIC))
                           "<clinit>" "()V" nil nil)]
      (.visitCode ci)
      (doseq [[i body] bodies]
        ;; RT.readString(pr-str(body)) → Object → PUTSTATIC body_N
        (.visitLdcInsn ci (pr-str body))
        (.visitMethodInsn ci INVOKESTATIC RT-CLASS "readString"
                          (str "(" STR ")" OBJ) false)
        (.visitFieldInsn ci PUTSTATIC cls-name (body-field i) OBJ))
      (.visitInsn ci RETURN)
      (.visitMaxs ci (int 2) (int 0))
      (.visitEnd ci))

    ;; ── run() method ──────────────────────────────────────────────────────────
    (let [mv     (.visitMethod cw (int (+ ACC-PUBLIC ACC-STATIC))
                               "run" "()V" nil nil)
          lbls   (mapv (fn [_] (Label.)) bc-vec)
          end-lbl (Label.)]

      (.visitCode mv)

      (doseq [i (range n-instrs)]
        (.visitLabel mv (lbls i))
        (let [{:keys [op body s f s-sig f-sig]} (bc-vec i)
              op   (int op)

              ;; Helper: emit body evaluation, leave result on stack.
              ;; 23E: try inline-emit! first (no EVAL_FN call for common patterns).
              ;; Falls back to EVAL_FN for complex bodies.
              eval-body!
              (fn []
                (if body
                  (or (inline-emit! mv cls-name body)
                      ;; Fallback: call EVAL_FN.invoke(body-field)
                      (do (.visitFieldInsn mv GETSTATIC cls-name "EVAL_FN" IFN-DESC)
                          (.visitFieldInsn mv GETSTATIC cls-name (body-field i) OBJ)
                          (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                                            IFN-INVOKE-SIG true)))
                  (.visitInsn mv ACONST-NULL)))

              ;; Helper: emit a signal throw via SIGNAL_FN IFn field.
              ;; SIGNAL_FN.invoke(sig-name) always throws ExceptionInfo.
              ;; Using INVOKEINTERFACE avoids INVOKESTATIC to jvm_codegen which
              ;; fails under DynamicClassLoader class isolation.
              emit-signal!
              (fn [sig]
                (.visitFieldInsn mv GETSTATIC cls-name "SIGNAL_FN" IFN-DESC)
                (.visitLdcInsn mv (name sig))
                (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                                  IFN-INVOKE-SIG true)
                ;; SIGNAL_FN always throws. Pop the nominally-returned value
                ;; (unreachable) so the JVM verifier sees an empty stack.
                (.visitInsn mv POP)
                (.visitInsn mv ACONST-NULL)
                (.visitInsn mv ATHROW))]

          (case op
            ;; 0 HALT
            0 (.visitInsn mv RETURN)

            ;; 1 EXEC — eval body, POP, GOTO fall
            1 (do (when body (eval-body!) (.visitInsn mv POP))
                  (when s (.visitJumpInsn mv GOTO (lbls s))))

            ;; 2 EXEC-S — eval; non-null → success, null → fall
            2 (do (eval-body!)
                  (let [fail-lbl (lbls f)]
                    (.visitJumpInsn mv IFNULL fail-lbl)
                    ;; success branch
                    (if s-sig
                      (emit-signal! s-sig)
                      (.visitJumpInsn mv GOTO (lbls s)))
                    ;; fall through to fail label (already placed)
                    ))

            ;; 3 EXEC-F — eval; null → failure, non-null → fall
            3 (do (eval-body!)
                  (let [ok-lbl (if s (lbls s) end-lbl)]
                    (.visitJumpInsn mv IFNONNULL ok-lbl)
                    ;; failure branch
                    (if f-sig
                      (emit-signal! f-sig)
                      (.visitJumpInsn mv GOTO (lbls f)))
                    (.visitLabel mv ok-lbl)))

            ;; 4 EXEC-SF — eval; non-null → s, null → f
            4 (do (eval-body!)
                  (let [fail-lbl (Label.)]
                    (.visitJumpInsn mv IFNULL fail-lbl)
                    ;; success
                    (if s-sig
                      (emit-signal! s-sig)
                      (.visitJumpInsn mv GOTO (lbls s)))
                    ;; failure
                    (.visitLabel mv fail-lbl)
                    (if f-sig
                      (emit-signal! f-sig)
                      (.visitJumpInsn mv GOTO (lbls f)))))

            ;; 5 JUMP — eval body (if any), GOTO s
            5 (do (when body (eval-body!) (.visitInsn mv POP))
                  (.visitJumpInsn mv GOTO (lbls (int s))))

            ;; 6 SIGNAL
            6 (emit-signal! body)

            ;; default
            (.visitInsn mv RETURN))))

      (.visitLabel mv end-lbl)
      (.visitInsn mv RETURN)
      (.visitMaxs mv (int 4) (int 2))
      (.visitEnd mv))

    (.visitEnd cw)
    (.toByteArray cw)))

;; ── Class loader cache ────────────────────────────────────────────────────────

(def ^:private class-cache (atom {}))

(defn load-program
  "Compile src to JVM bytecode and load the class.
   Returns a zero-arg fn that calls the generated static run() method.
   Results are cached by source string hash.

   Before invoking run(), this function sets EVAL_FN and all 23E inline
   IFn helper fields on the generated class."
  [src]
  (or (get @class-cache src)
      (let [bc       (compile-to-class src)
            cls-name (.replace (gen-class-name src) "/" ".")
            dcl      (DynamicClassLoader.)
            cls      (.defineClass dcl cls-name bc nil)
            ;; Set EVAL_FN field
            eval-field (.getField cls "EVAL_FN")
            _          (.set eval-field nil SNOBOL4clojure.operators/EVAL!)
            ;; Set all 23E inline IFn helper fields
            inline-fn-vals {"$$_FN"    $$_FN
                            "SET_FN"   SET_FN
                            "PRINT_FN" PRINT_FN
                            "ADD_FN"   ADD_FN
                            "SUB_FN"   SUB_FN
                            "MUL_FN"   MUL_FN
                            "DIV_FN"   DIV_FN
                            "LT_FN"    LT_FN
                            "GT_FN"    GT_FN
                            "LE_FN"    LE_FN
                            "GE_FN"    GE_FN
                            "EQ_FN"    EQ_FN
                            "NEQ_FN"   NEQ_FN
                            "SIGNAL_FN" SIGNAL_FN
                            ;; 23E extensions
                            "CONCAT_FN" CONCAT_FN
                            "SIZE_FN"   SIZE_FN
                            "STR_FN"    STR_FN}
            _  (doseq [[fld-name fld-val] inline-fn-vals]
                 (.set (.getField cls fld-name) nil fld-val))
            method   (.getMethod cls "run" (into-array Class []))
            run-fn   (fn []
                       ;; Refresh EVAL_FN in case of namespace reload
                       (.set eval-field nil SNOBOL4clojure.operators/EVAL!)
                       (.invoke method nil (into-array Object [])))]
        (swap! class-cache assoc src run-fn)
        run-fn)))

(defn clear-class-cache!
  "Evict all entries from the JVM class cache."
  []
  (reset! class-cache {})
  nil)

;; ── Execute ───────────────────────────────────────────────────────────────────

(defn run-jvm!
  "Run src through the JVM-compiled path. Output goes to *out*."
  [src]
  (env/GLOBALS (find-ns 'SNOBOL4clojure.jvm-codegen))
  (reset! env/STNO 0)
  (reset! env/<STNO> {})
  (reset! env/<LABL> {})
  (reset! env/<CODE> {})
  (reset! env/<FUNS> {})
  (reset! &STCOUNT 0)
  (let [run-fn (load-program src)]
    (try
      (run-fn)
      (catch java.lang.reflect.InvocationTargetException e
        (let [cause (.getCause e)]
          (if (instance? clojure.lang.ExceptionInfo cause)
            (when-not (contains? #{:end :return :freturn :nreturn}
                                 (get (ex-data cause) :snobol/signal))
              (throw cause))
            (throw (or cause e))))))))

(defn run-jvm-captured!
  "Run src through JVM-compiled path and return captured stdout as string."
  [src]
  (with-out-str (run-jvm! src)))

;; ── Benchmark ────────────────────────────────────────────────────────────────

(defn bench-compare-jvm
  "Compare interpreter (RUN+CODE-memo) vs JVM-compiled (run-jvm!) on src.
   Warms both paths before timing.
   Returns {:interpreter-ms :jvm-ms :ratio :outputs-match}."
  [src n]
  (let [reset-env! (fn []
                     (env/GLOBALS (find-ns 'SNOBOL4clojure.jvm-codegen))
                     (reset! env/STNO 0) (reset! env/<STNO> {})
                     (reset! env/<LABL> {}) (reset! env/<CODE> {})
                     (reset! env/<FUNS> {}))

        run-interp (fn []
                     (reset-env!)
                     (with-out-str
                       (try (rt/RUN (comp/CODE-memo src))
                            (catch clojure.lang.ExceptionInfo e
                              (when-not (contains? #{:end :return :freturn :nreturn}
                                                   (get (ex-data e) :snobol/signal))
                                (throw e))))))

        run-fn     (do (reset-env!) (load-program src))
        run-jvm    (fn []
                     (reset-env!)
                     (with-out-str
                       (try (run-fn)
                            (catch java.lang.reflect.InvocationTargetException e
                              (let [cause (.getCause e)]
                                (when-not (and (instance? clojure.lang.ExceptionInfo cause)
                                              (contains? #{:end :return :freturn :nreturn}
                                                         (get (ex-data cause) :snobol/signal)))
                                  (throw (or cause e))))))))]

    (dotimes [_ 30] (run-interp))
    (dotimes [_ 30] (run-jvm))

    (let [i-out (atom "") j-out (atom "")
          t0 (System/nanoTime)
          _  (dotimes [_ n] (reset! i-out (run-interp)))
          i-ms (/ (/ (- (System/nanoTime) t0) n) 1e6)
          t1 (System/nanoTime)
          _  (dotimes [_ n] (reset! j-out (run-jvm)))
          j-ms (/ (/ (- (System/nanoTime) t1) n) 1e6)]
      {:interpreter-ms  (double i-ms)
       :jvm-ms          (double j-ms)
       :ratio           (double (/ i-ms j-ms))
       :outputs-match   (clojure.core/= @i-out @j-out)})))

;; ── Initialize 23E inline IFn references at namespace load time ─────────────
(init-inline-fns!)
