(ns SNOBOL4clojure.jvm-codegen
  "Stage 23D — JVM Bytecode Generation

   Compiles SNOBOL4 IR all the way to JVM .class bytecode.
   Each SNOBOL4 program becomes one Java class with a static run() method.
   The JVM JIT compiles the resulting bytecode to native x64 machine code.

   ## Call convention

   Generated classes call EVAL! via INVOKEINTERFACE on clojure.lang.IFn,
   using a static IFn field pre-populated in jvm_codegen itself.  This avoids
   any reference to SNOBOL4clojure.operators in the generated class's constant
   pool (which would fail to resolve at class-load time before the Clojure
   DynamicClassLoader has loaded operators.clj).

   Generated class structure:
     static Object EVAL_FN;   // = jvm_codegen.EVAL_FN (set before run! is called)
     static Object body_N;    // one field per instruction that has a body
     static { body_N = RT.readString(pr-str(body)); ... }
     public static void run() { ... GETFIELD EVAL_FN, INVOKEINTERFACE IFn.invoke ... }

   The generated class only references:
     - java/lang/Object         (always available)
     - clojure/lang/IFn         (always available — part of Clojure runtime jar)
     - clojure/lang/RT          (always available)
     - clojure/lang/ExceptionInfo (always available)
     - SNOBOL4clojure/jvm_codegen (the class that compiled it — always loaded)

   ## Public API

     (compile-to-class src)       → byte[] (JVM .class bytecode)
     (load-program src)           → zero-arg fn (wraps static run() via reflection)
     (run-jvm! src)               → nil (output via *out*)
     (run-jvm-captured! src)      → String (captured stdout)
     (bench-compare-jvm src n)    → {:interpreter-ms :jvm-ms :ratio :outputs-match}
     (clear-class-cache!)         → nil

   ## Design invariant

   Identical output to interpreter (runtime.clj RUN) on every program.
   Validated against 1000+ worm corpus programs.
  "
  (:import [clojure.asm ClassWriter MethodVisitor Label Opcodes]
           [clojure.lang DynamicClassLoader IFn RT])
  (:require [clojure.string          :as str]
            [SNOBOL4clojure.compiler :as comp]
            [SNOBOL4clojure.vm       :as vm]
            [SNOBOL4clojure.env      :as env
             :refer [&STCOUNT &STLIMIT snobol-steplimit!]]
            [SNOBOL4clojure.runtime  :as rt]))

;; ── ASM opcode integer constants ──────────────────────────────────────────────

(def ^:private ^:const ACC-PUBLIC   (int Opcodes/ACC_PUBLIC))
(def ^:private ^:const ACC-STATIC   (int Opcodes/ACC_STATIC))
(def ^:private ^:const ACC-SUPER    (int Opcodes/ACC_SUPER))
(def ^:private ^:const V1-8         (int 52))
(def ^:private ^:const RETURN       (int Opcodes/RETURN))
(def ^:private ^:const ARETURN      (int Opcodes/ARETURN))
(def ^:private ^:const ALOAD-0      (int Opcodes/ALOAD))
(def ^:private ^:const ASTORE       (int Opcodes/ASTORE))
(def ^:private ^:const GETSTATIC    (int Opcodes/GETSTATIC))
(def ^:private ^:const PUTSTATIC    (int Opcodes/PUTSTATIC))
(def ^:private ^:const INVOKESTATIC (int Opcodes/INVOKESTATIC))
(def ^:private ^:const INVOKEINTERFACE (int Opcodes/INVOKEINTERFACE))
(def ^:private ^:const INVOKEVIRTUAL (int Opcodes/INVOKEVIRTUAL))
(def ^:private ^:const INVOKESPECIAL (int Opcodes/INVOKESPECIAL))
(def ^:private ^:const GOTO         (int Opcodes/GOTO))
(def ^:private ^:const IFNULL       (int Opcodes/IFNULL))
(def ^:private ^:const IFNONNULL    (int Opcodes/IFNONNULL))
(def ^:private ^:const ATHROW       (int Opcodes/ATHROW))
(def ^:private ^:const POP          (int Opcodes/POP))
(def ^:private ^:const DUP          (int Opcodes/DUP))
(def ^:private ^:const ACONST-NULL  (int Opcodes/ACONST_NULL))

;; ── Descriptor constants ──────────────────────────────────────────────────────

(def ^:private OBJ       "Ljava/lang/Object;")
(def ^:private STR       "Ljava/lang/String;")
(def ^:private IFN-DESC  "Lclojure/lang/IFn;")
(def ^:private IFN-CLASS "clojure/lang/IFn")
(def ^:private RT-CLASS  "clojure/lang/RT")
(def ^:private JC-CLASS  "SNOBOL4clojure/jvm_codegen")  ; THIS class
(def ^:private IFN-INVOKE-SIG (str "(" OBJ ")" OBJ))     ; IFn.invoke(Object)->Object
(def ^:private THROW-SIG  (str "(" STR ")Lclojure/lang/ExceptionInfo;"))

;; ── Static EVAL! IFn reference (set once, used by all generated classes) ─────
;;
;; The generated bytecode does:
;;   GETSTATIC SNOBOL4clojure/jvm_codegen EVAL_FN Lclojure/lang/IFn;
;;   <push body>
;;   INVOKEINTERFACE clojure/lang/IFn invoke (Ljava/lang/Object;)Ljava/lang/Object;
;;
;; This means jvm_codegen is always referenced — which is safe because it's the
;; class that called compile-to-class and is guaranteed already loaded.

(declare EVAL_FN)

;; ── Signal helpers — called from generated bytecode via INVOKESTATIC ─────────

(defn ^clojure.lang.ExceptionInfo make-signal
  "Create a SNOBOL4 ExceptionInfo. Called from JVM-compiled programs."
  [^String sig-name]
  (ex-info sig-name {:snobol/signal (keyword sig-name)}))

;; ── Class name generation ─────────────────────────────────────────────────────

(defn gen-class-name
  "Generate a stable JVM internal class name for a SNOBOL4 source string.
   The class is in the SNOBOL4clojure package to match jvm_codegen's package."
  [src]
  (str "SNOBOL4clojure/SnobolProg" (format "%08x" (Math/abs (hash src)))))

;; ── Bytecode emitter ─────────────────────────────────────────────────────────

(defn compile-to-class
  "Compile SNOBOL4 source to JVM bytecode.
   Returns byte[] — a valid .class file.

   Generated class layout:
     public static IFn EVAL_FN;     // set externally before run() is called
     public static Object body_N;   // one field per instruction body
     static { body_N = RT.readString(...); ... }
     public static void run() { ... }
  "
  [src]
  (let [bc-vec    (vm/compile-src src)
        n-instrs  (count bc-vec)
        cls-name  (gen-class-name src)
        cw        (ClassWriter. (int ClassWriter/COMPUTE_FRAMES))

        ;; Collect (index, body) pairs for instructions that have a body
        bodies    (into [] (keep-indexed (fn [i {:keys [body]}]
                                           (when body [i body]))
                                         bc-vec))
        body-field (fn [i] (str "body_" i))]

    ;; ── Class header ──────────────────────────────────────────────────────────
    (.visit cw V1-8 (int (+ ACC-PUBLIC ACC-SUPER))
            cls-name nil "java/lang/Object" nil)

    ;; ── Static field: EVAL_FN (IFn, set from Clojure before run() is called) ─
    (.visitField cw (int (+ ACC-PUBLIC ACC-STATIC))
                 "EVAL_FN" IFN-DESC nil nil)

    ;; ── Static body fields (Object, one per instruction that has a body) ─────
    (doseq [[i _] bodies]
      (.visitField cw (int (+ ACC-PUBLIC ACC-STATIC))
                   (body-field i) OBJ nil nil))

    ;; ── <clinit>: initialise body fields via RT.readString ────────────────────
    (let [ci (.visitMethod cw (int (+ ACC-PUBLIC ACC-STATIC))
                           "<clinit>" "()V" nil nil)]
      (.visitCode ci)
      (doseq [[i body] bodies]
        ;; RT.readString(pr-str(body)) → Object → PUTSTATIC body_N
        (.visitLdcInsn ci (pr-str body))
        (.visitMethodInsn ci INVOKESTATIC RT-CLASS "readString"
                          (str "(" STR ")" OBJ) false)
        (.visitFieldInsn ci PUTSTATIC cls-name (body-field i) OBJ))
      (.visitInsn ci RETURN)
      (.visitMaxs ci (int 2) (int 0))
      (.visitEnd ci))

    ;; ── run() method ──────────────────────────────────────────────────────────
    (let [mv     (.visitMethod cw (int (+ ACC-PUBLIC ACC-STATIC))
                               "run" "()V" nil nil)
          lbls   (mapv (fn [_] (Label.)) bc-vec)
          end-lbl (Label.)]

      (.visitCode mv)

      (doseq [i (range n-instrs)]
        (.visitLabel mv (lbls i))
        (let [{:keys [op body s f s-sig f-sig]} (bc-vec i)
              op   (int op)

              ;; Helper: push EVAL_FN + body field, call IFn.invoke, leave result on stack
              eval-body!
              (fn []
                (if body
                  (do (.visitFieldInsn mv GETSTATIC cls-name "EVAL_FN" IFN-DESC)
                      (.visitFieldInsn mv GETSTATIC cls-name (body-field i) OBJ)
                      (.visitMethodInsn mv INVOKEINTERFACE IFN-CLASS "invoke"
                                        IFN-INVOKE-SIG true))
                  (.visitInsn mv ACONST-NULL)))

              ;; Helper: emit a signal throw (LDC + INVOKESTATIC + ATHROW)
              emit-signal!
              (fn [sig]
                (.visitLdcInsn mv (name sig))
                (.visitMethodInsn mv INVOKESTATIC JC-CLASS "make_signal"
                                  THROW-SIG false)
                (.visitInsn mv ATHROW))]

          (case op
            ;; 0 HALT
            0 (.visitInsn mv RETURN)

            ;; 1 EXEC — eval body, POP, GOTO fall
            1 (do (when body (eval-body!) (.visitInsn mv POP))
                  (when s (.visitJumpInsn mv GOTO (lbls s))))

            ;; 2 EXEC-S — eval; non-null → success, null → fall
            2 (do (eval-body!)
                  (let [fail-lbl (lbls f)]
                    (.visitJumpInsn mv IFNULL fail-lbl)
                    ;; success branch
                    (if s-sig
                      (emit-signal! s-sig)
                      (.visitJumpInsn mv GOTO (lbls s)))
                    ;; fall through to fail label (already placed)
                    ))

            ;; 3 EXEC-F — eval; null → failure, non-null → fall
            3 (do (eval-body!)
                  (let [ok-lbl (if s (lbls s) end-lbl)]
                    (.visitJumpInsn mv IFNONNULL ok-lbl)
                    ;; failure branch
                    (if f-sig
                      (emit-signal! f-sig)
                      (.visitJumpInsn mv GOTO (lbls f)))
                    (.visitLabel mv ok-lbl)))

            ;; 4 EXEC-SF — eval; non-null → s, null → f
            4 (do (eval-body!)
                  (let [fail-lbl (Label.)]
                    (.visitJumpInsn mv IFNULL fail-lbl)
                    ;; success
                    (if s-sig
                      (emit-signal! s-sig)
                      (.visitJumpInsn mv GOTO (lbls s)))
                    ;; failure
                    (.visitLabel mv fail-lbl)
                    (if f-sig
                      (emit-signal! f-sig)
                      (.visitJumpInsn mv GOTO (lbls f)))))

            ;; 5 JUMP — eval body (if any), GOTO s
            5 (do (when body (eval-body!) (.visitInsn mv POP))
                  (.visitJumpInsn mv GOTO (lbls (int s))))

            ;; 6 SIGNAL
            6 (emit-signal! body)

            ;; default
            (.visitInsn mv RETURN))))

      (.visitLabel mv end-lbl)
      (.visitInsn mv RETURN)
      (.visitMaxs mv (int 4) (int 2))
      (.visitEnd mv))

    (.visitEnd cw)
    (.toByteArray cw)))

;; ── Class loader cache ────────────────────────────────────────────────────────

(def ^:private class-cache (atom {}))

(defn load-program
  "Compile src to JVM bytecode and load the class.
   Returns a zero-arg fn that calls the generated static run() method.
   Results are cached by source string hash.

   Before invoking run(), this function sets the EVAL_FN field on the
   generated class to the current EVAL! function."
  [src]
  (or (get @class-cache src)
      (let [bc       (compile-to-class src)
            cls-name (.replace (gen-class-name src) "/" ".")
            dcl      (DynamicClassLoader.)
            cls      (.defineClass dcl cls-name bc nil)
            ;; Set EVAL_FN field to our EVAL! function
            eval-field (.getField cls "EVAL_FN")
            _          (.set eval-field nil SNOBOL4clojure.operators/EVAL!)
            method   (.getMethod cls "run" (into-array Class []))
            run-fn   (fn []
                       ;; Refresh EVAL_FN in case of namespace reload
                       (.set eval-field nil SNOBOL4clojure.operators/EVAL!)
                       (.invoke method nil (into-array Object [])))]
        (swap! class-cache assoc src run-fn)
        run-fn)))

(defn clear-class-cache!
  "Evict all entries from the JVM class cache."
  []
  (reset! class-cache {})
  nil)

;; ── Execute ───────────────────────────────────────────────────────────────────

(defn run-jvm!
  "Run src through the JVM-compiled path. Output goes to *out*."
  [src]
  (env/GLOBALS (find-ns 'SNOBOL4clojure.jvm-codegen))
  (reset! env/STNO 0)
  (reset! env/<STNO> {})
  (reset! env/<LABL> {})
  (reset! env/<CODE> {})
  (reset! env/<FUNS> {})
  (reset! &STCOUNT 0)
  (let [run-fn (load-program src)]
    (try
      (run-fn)
      (catch java.lang.reflect.InvocationTargetException e
        (let [cause (.getCause e)]
          (if (instance? clojure.lang.ExceptionInfo cause)
            (when-not (contains? #{:end :return :freturn :nreturn}
                                 (get (ex-data cause) :snobol/signal))
              (throw cause))
            (throw (or cause e))))))))

(defn run-jvm-captured!
  "Run src through JVM-compiled path and return captured stdout as string."
  [src]
  (with-out-str (run-jvm! src)))

;; ── Benchmark ────────────────────────────────────────────────────────────────

(defn bench-compare-jvm
  "Compare interpreter (RUN+CODE-memo) vs JVM-compiled (run-jvm!) on src.
   Warms both paths before timing.
   Returns {:interpreter-ms :jvm-ms :ratio :outputs-match}."
  [src n]
  (let [reset-env! (fn []
                     (env/GLOBALS (find-ns 'SNOBOL4clojure.jvm-codegen))
                     (reset! env/STNO 0) (reset! env/<STNO> {})
                     (reset! env/<LABL> {}) (reset! env/<CODE> {})
                     (reset! env/<FUNS> {}))

        run-interp (fn []
                     (reset-env!)
                     (with-out-str
                       (try (rt/RUN (comp/CODE-memo src))
                            (catch clojure.lang.ExceptionInfo e
                              (when-not (contains? #{:end :return :freturn :nreturn}
                                                   (get (ex-data e) :snobol/signal))
                                (throw e))))))

        run-fn     (do (reset-env!) (load-program src))
        run-jvm    (fn []
                     (reset-env!)
                     (with-out-str
                       (try (run-fn)
                            (catch java.lang.reflect.InvocationTargetException e
                              (let [cause (.getCause e)]
                                (when-not (and (instance? clojure.lang.ExceptionInfo cause)
                                              (contains? #{:end :return :freturn :nreturn}
                                                         (get (ex-data cause) :snobol/signal)))
                                  (throw (or cause e))))))))]

    (dotimes [_ 30] (run-interp))
    (dotimes [_ 30] (run-jvm))

    (let [i-out (atom "") j-out (atom "")
          t0 (System/nanoTime)
          _  (dotimes [_ n] (reset! i-out (run-interp)))
          i-ms (/ (/ (- (System/nanoTime) t0) n) 1e6)
          t1 (System/nanoTime)
          _  (dotimes [_ n] (reset! j-out (run-jvm)))
          j-ms (/ (/ (- (System/nanoTime) t1) n) 1e6)]
      {:interpreter-ms  (double i-ms)
       :jvm-ms          (double j-ms)
       :ratio           (double (/ i-ms j-ms))
       :outputs-match   (clojure.core/= @i-out @j-out)})))
